plugins {
    id 'java-library'
    id 'maven-publish'
    id 'eclipse'
    id 'idea'
    id 'net.neoforged.gradle.userdev' version '7.1.26'
}

version = mod_version
group = mod_group_id

base {
    archivesName = mod_file_name
}

repositories {
    maven {
        url "https://www.cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
    mavenCentral()
}

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

sourceSets.main.resources {
    srcDir('src/generated/resources')
}

println "Java: ${System.getProperty 'java.version'}, JVM: ${System.getProperty 'java.vm.version'} (${System.getProperty 'java.vendor'}), Arch: ${System.getProperty 'os.arch'}"

runs {
    configureEach {
        workingDirectory project.layout.projectDirectory.dir('runs').dir(name)
        modSource project.sourceSets.main
    }

    data {
        arguments.addAll '--mod', mod_id, '--all',
                '--output', file('src/generated/resources/').absolutePath,
                '--existing', file('src/main/resources/').absolutePath
    }
}

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

dependencies {
    implementation "net.neoforged:neoforge:${neo_version}"
    compileOnly "org.spongepowered:mixin:0.8.5"
    annotationProcessor "org.spongepowered:mixin:0.8.5:processor"
    compileOnly "io.github.llamalad7:mixinextras-common:0.5.3"
    implementation "curse.maven:curios-309927:6529130"
    implementation "curse.maven:attributefix-280510:7115922"
    implementation "curse.maven:max-health-fix-492246:5824111"
    runtimeOnly "curse.maven:bookshelf-228525:7606240"
    runtimeOnly "curse.maven:prickle-1023259:6961457"
    implementation "curse.maven:selene-499980:8065893"
    implementation "curse.maven:jei-238222:7416540"
    implementation "curse.maven:appleskin-248787:7854442"
    implementation "curse.maven:placebo-283644:6926281"
    implementation "curse.maven:apothic-attributes-898963:7445079"
    implementation "curse.maven:irons-spells-n-spellbooks-855414:7907341"
    runtimeOnly "curse.maven:irons-lib-1492763:7907336"
    implementation "curse.maven:geckolib-388172:7707149"
    implementation "curse.maven:playeranimator-658587:6024462"
}

tasks.withType(ProcessResources).configureEach {
    def replaceProperties = [
        minecraft_version: minecraft_version,
        minecraft_version_range: minecraft_version_range,
        neo_version: neo_version,
        loader_version_range: loader_version_range,
        mod_id: mod_id,
        mod_name: mod_name,
        mod_license: mod_license,
        mod_version: mod_version,
        mod_authors: mod_authors,
        mod_description: mod_description
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml', 'pack.mcmeta']) {
        expand replaceProperties
    }
}

jar {
    manifest {
        attributes([
                "Specification-Title"     : mod_id,
                "Specification-Vendor"    : mod_authors,
                "Specification-Version"   : "1",
                "Implementation-Title"    : project.name,
                "Implementation-Version"  : project.jar.archiveVersion,
                "Implementation-Vendor"   : mod_authors,
                "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
